---
- name: Create a directory if it does not exist [ /etc/systemd/system/rabbitmq-server.service.d ]
  ansible.builtin.file:
    path: /etc/systemd/system/rabbitmq-server.service.d
    state: directory
    mode: '0755'

- name: Copy limits.conf template file to [ /etc/systemd/system/rabbitmq-server.service.d ]
  ansible.builtin.template:
    src: templates/rabbitmq-server.service.d_limits.conf
    dest: /etc/systemd/system/rabbitmq-server.service.d/limits.conf
    owner: root
    group: root
    mode: '0644'
